name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0', '6.0.x' ]

    defaults:
      run:
        working-directory: ./src/
  
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
      - name: Install dependencies
        run: dotnet restore Example.Code.sln
      - name: Build
        run: dotnet build Example.Code.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test Example.Code.sln --no-restore --verbosity normal
